import React, { useState } from 'react';
import { 
  Printer, 
  Download, 
  Copy, 
  Check, 
  FileText, 
  Sparkles, 
  ShieldCheck, 
  Layers, 
  Award,
  BookOpen
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { DifferentiatedLessonPlan } from './types';
import { EXEMPLARY_DIFFERENTIATED_LESSON_PLAN } from './spedEbMasterData';

interface SpedEbLessonExporterProps {
  plan?: DifferentiatedLessonPlan;
}

export const SpedEbLessonExporter: React.FC<SpedEbLessonExporterProps> = ({
  plan = EXEMPLARY_DIFFERENTIATED_LESSON_PLAN
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  const generateMarkdown = () => {
    return `# EduPulse Differentiated Lesson Plan: ${plan.standardCode}
## Standard: ${plan.standardTitle}

### 1. Measurable Objectives (SWBAT)
- **General Ed SWBAT:** ${plan.swbatGeneral}
- **SPED Tier 3 SWBAT:** ${plan.swbatSpedTier3}
- **Emergent Bilingual SWBAT:** ${plan.swbatEbLinguistic}
- **STAAR Alt 2 Essence:** ${plan.staarAlt2Essence}

### 2. Universal Design for Learning (UDL 3.0) Framework
- **Multiple Means of Engagement:**
${plan.udlEngagement.map(e => `  - ${e}`).join('\n')}
- **Multiple Means of Representation:**
${plan.udlRepresentation.map(r => `  - ${r}`).join('\n')}
- **Multiple Means of Action & Expression:**
${plan.udlActionExpression.map(a => `  - ${a}`).join('\n')}

### 3. IEP / Section 504 Designated Supports
${plan.designatedSupports.map(s => `- [x] ${s}`).join('\n')}

### 4. TELPAS Language Scaffolds
- **Beginning:** ${plan.telpasSentenceStemsByTier.Beginning.join(' | ')}
- **Intermediate:** ${plan.telpasSentenceStemsByTier.Intermediate.join(' | ')}
- **Advanced:** ${plan.telpasSentenceStemsByTier.Advanced.join(' | ')}
- **Advanced High:** ${plan.telpasSentenceStemsByTier['Advanced High'].join(' | ')}

### 5. High-Tech AAC Speech Board Core Vocabulary
${plan.aacKeyVocab.join(', ')}

---
*Generated by EduPulse Sovereign Educator Platform • Legally Compliant with IDEA 34 CFR § 300.320 & LPAC 19 TAC § 89*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJson = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(plan, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `edupulse_differentiated_plan_${plan.standardCode}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="space-y-6 print:p-0">
      
      {/* HEADER BANNER */}
      <div className="rounded-2xl bg-gradient-to-r from-amber-950/80 via-slate-900 to-indigo-950/80 border-2 border-amber-500/40 p-6 shadow-xl space-y-3 print:hidden">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <Badge className="bg-amber-500/20 text-amber-300 border-amber-500/50 text-xs px-3 py-1 font-mono uppercase font-bold">
              <FileText className="w-3.5 h-3.5 mr-1.5 inline" /> Differentiated Lesson Plan Exporter
            </Badge>
            <Badge className="bg-emerald-500/20 text-emerald-300 border-emerald-500/40 text-xs">
              IEP • 504 • LPAC Audit-Proof
            </Badge>
          </div>

          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              onClick={handleCopyMarkdown}
              className="h-8 text-xs bg-slate-950 border-slate-700 text-slate-200 hover:bg-slate-800"
            >
              {copied ? <Check className="w-3.5 h-3.5 mr-1 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 mr-1" />}
              {copied ? 'Copied Markdown!' : 'Copy Markdown'}
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={handleDownloadJson}
              className="h-8 text-xs bg-slate-950 border-slate-700 text-slate-200 hover:bg-slate-800"
            >
              <Download className="w-3.5 h-3.5 mr-1 text-cyan-400" /> Export JSON
            </Button>
            <Button
              size="sm"
              onClick={handlePrint}
              className="h-8 text-xs bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold"
            >
              <Printer className="w-3.5 h-3.5 mr-1" /> Print Lesson Document
            </Button>
          </div>
        </div>

        <h2 className="text-2xl md:text-3xl font-extrabold text-slate-100">
          Universal Differentiated Lesson Document & Compliance Portfolio
        </h2>
        <p className="text-slate-300 text-sm leading-relaxed max-w-3xl">
          Unified multi-tier lesson blueprint integrating general education objectives, SPED accommodations, TELPAS language scaffolds, UDL 3.0 principles, and AAC speech vocabulary.
        </p>
      </div>

      {/* PRINTABLE LESSON PLAN CANVAS */}
      <Card className="bg-slate-900/95 border-2 border-amber-500/40 p-6 md:p-8 space-y-6 shadow-2xl print:bg-white print:text-black print:border-none print:shadow-none">
        
        {/* DOCUMENT HEADER */}
        <div className="border-b-2 border-amber-500/40 pb-4 space-y-2 print:border-black">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Badge className="bg-amber-500/20 text-amber-300 border-amber-500/50 font-mono text-sm px-3 py-1 font-bold print:bg-transparent print:text-black print:border-black">
                {plan.standardCode}
              </Badge>
              <span className="text-sm font-bold text-slate-300 print:text-black">1st Grade Mathematics</span>
            </div>
            <span className="text-xs text-slate-400 font-mono print:text-black">EduPulse Compliance v3.0</span>
          </div>

          <h3 className="text-2xl font-black text-slate-100 print:text-black">
            {plan.standardTitle}
          </h3>
        </div>

        {/* SECTION 1: OBJECTIVES */}
        <div className="space-y-3">
          <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider print:text-black">
            1. Tiered Measurable Objectives (SWBAT):
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
            <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 space-y-1 print:bg-gray-100 print:text-black">
              <span className="font-bold text-blue-400 print:text-black">General Education SWBAT:</span>
              <p className="text-slate-200 print:text-black">{plan.swbatGeneral}</p>
            </div>
            <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 space-y-1 print:bg-gray-100 print:text-black">
              <span className="font-bold text-indigo-400 print:text-black">SPED Tier 3 SWBAT:</span>
              <p className="text-slate-200 print:text-black">{plan.swbatSpedTier3}</p>
            </div>
            <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 space-y-1 print:bg-gray-100 print:text-black">
              <span className="font-bold text-emerald-400 print:text-black">Emergent Bilingual SWBAT:</span>
              <p className="text-slate-200 print:text-black">{plan.swbatEbLinguistic}</p>
            </div>
          </div>
        </div>

        {/* SECTION 2: UDL 3.0 MULTI-MODAL MATRIX */}
        <div className="space-y-3">
          <h4 className="text-xs font-bold text-indigo-400 uppercase tracking-wider print:text-black">
            2. Universal Design for Learning (UDL 3.0) Implementation:
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
            <div className="p-3 bg-slate-950 rounded-xl border border-indigo-500/30 space-y-1 print:bg-gray-100 print:text-black">
              <span className="font-bold text-indigo-300 print:text-black">Engagement (Why):</span>
              <ul className="list-disc list-inside text-slate-300 space-y-0.5 print:text-black">
                {plan.udlEngagement.map((item, i) => <li key={i}>{item}</li>)}
              </ul>
            </div>
            <div className="p-3 bg-slate-950 rounded-xl border border-cyan-500/30 space-y-1 print:bg-gray-100 print:text-black">
              <span className="font-bold text-cyan-300 print:text-black">Representation (What):</span>
              <ul className="list-disc list-inside text-slate-300 space-y-0.5 print:text-black">
                {plan.udlRepresentation.map((item, i) => <li key={i}>{item}</li>)}
              </ul>
            </div>
            <div className="p-3 bg-slate-950 rounded-xl border border-purple-500/30 space-y-1 print:bg-gray-100 print:text-black">
              <span className="font-bold text-purple-300 print:text-black">Action & Expression (How):</span>
              <ul className="list-disc list-inside text-slate-300 space-y-0.5 print:text-black">
                {plan.udlActionExpression.map((item, i) => <li key={i}>{item}</li>)}
              </ul>
            </div>
          </div>
        </div>

        {/* SECTION 3: DESIGNATED SUPPORTS */}
        <div className="space-y-3">
          <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider print:text-black">
            3. IEP / Section 504 Designated Supports Checklist:
          </h4>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2 text-xs">
            {plan.designatedSupports.map((supp, i) => (
              <div key={i} className="p-2.5 bg-slate-950 rounded-lg border border-slate-800 flex items-center gap-2 print:bg-gray-100 print:text-black">
                <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0 print:text-black" />
                <span className="text-slate-200 font-medium print:text-black">{supp}</span>
              </div>
            ))}
          </div>
        </div>

        {/* SECTION 4: TELPAS LINGUISTIC SCAFFOLDS */}
        <div className="space-y-3">
          <h4 className="text-xs font-bold text-teal-400 uppercase tracking-wider print:text-black">
            4. TELPAS Tiered Sentence Stems:
          </h4>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
            <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 space-y-1 print:bg-gray-100 print:text-black">
              <span className="font-bold text-teal-300 print:text-black">Beginning & Intermediate:</span>
              <ul className="list-disc list-inside text-slate-300 print:text-black">
                {plan.telpasSentenceStemsByTier.Beginning.map((s, i) => <li key={i}>&ldquo;{s}&rdquo;</li>)}
                {plan.telpasSentenceStemsByTier.Intermediate.map((s, i) => <li key={i}>&ldquo;{s}&rdquo;</li>)}
              </ul>
            </div>
            <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 space-y-1 print:bg-gray-100 print:text-black">
              <span className="font-bold text-cyan-300 print:text-black">Advanced & Advanced High:</span>
              <ul className="list-disc list-inside text-slate-300 print:text-black">
                {plan.telpasSentenceStemsByTier.Advanced.map((s, i) => <li key={i}>&ldquo;{s}&rdquo;</li>)}
                {plan.telpasSentenceStemsByTier['Advanced High'].map((s, i) => <li key={i}>&ldquo;{s}&rdquo;</li>)}
              </ul>
            </div>
          </div>
        </div>

      </Card>

    </div>
  );
};
